server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://YOUR_SERVER:3306/YOUR_DATABASE?characterEncoding=utf-8&createDatabaseIfNotExist=true
    username: YOUR_USERNAME
    platform: mysql
    password: YOUR_PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: false
